---
title: "Assignment 01: Quarto Notes"
date: "2026-08-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
source(here::here("R", "slide-things.R"))
```


This is the first regular assignment for the course.

## Task 1: Write up your notes for the first class meeting

You should have taken notes during the first class meeting. If you are taking
notes in something other than Quarto, that's fine. If you didn't take notes at
all, you should think about starting to take notes. What I want you to do is
make a Quarto file within some RStudio project. (Loose advice: I like to have a
"scratch" folder, in the sense of a
[scratchpad](https://en.wikipedia.org/wiki/Scratchpad), where I can create
single-use script files or one-off quick documents that are not yet projects.)
Choose a name for this file and, in the file itself explain your choice of file
name. In addition, tell me where exactly on your computer the this file is, and
why it is there.

For the remainder of the quarto file, feel free to write up or include whatever
you want from the first class meeting. Or, use it to practice the rudiments of
RMarkdown based on the content of the second batch of slides from Week 1. You
can include code snippets, bibliographical references, experiments with document
structure or formatting, or whatever else you think would be useful for you.

## Task 2: Render your notes to PDF and submit it to Canvas

Create a PDF version of your file. There will be a Canvas assignment where you can upload the PDF file.
