---
title: "Assignment 02: Find Some Data"
date: "2026-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
source(here::here("R", "slide-things.R"))
```


To do data analysis, we need some data.

## Task 1: Data Sources

Look at the [list of practice data sources](https://mptc.io/content/) on the
course website. Pick one of the data sources. Alternatively, and better, find a
similar source for yourself that you are actually interested in. It doesn't have
to be something you already know how to use or work with. Indeed, it's probably
better if it isn't. But you should want to know about it. In any case, choose at
least one table from whatever the source is and download the data.

## Task 2: Set up a Project

Set up a new R project in RStudio, and save the data file in a subdirectory of
that project, named `data`. Create a new Quarto document in the project, and
write a short paragraph about the data you downloaded, saying what format you
think it is in, how you obtained it, what it contains, what you think you
could learn from it, and why you find that interesting.

## Task 3: Be Ready to Share Your Work

We'll be going over the projects in class, so be ready to share what you've done.
