---
title: "1. The Idea of Your Computer"
date: 2023-08-29
date-format: full
---

```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## This week ...

## General Background Reading

- @christensen19:_trans_reprod_social_scien_resear

## Also ... 

-   Read the [content](/content/index.qmd), [examples](/example/index.qmd), and [assignments](/assignment/index.qmd) pages for this class.

## Slides

```{=html}
<script type="application/javascript">

function resizeIFrameToFitContent( iFrame ) {

   iFrame.width  = document.getElementById("quarto-document-content").clientWidth;
   iFrame.height  = (document.getElementById("quarto-document-content").clientWidth * 0.5625)
}

window.addEventListener('DOMContentLoaded', function(e) {

    var iFrame = document.getElementById( 'quartoframe' );
    resizeIFrameToFitContent( iFrame );
    } );

</script>
<iframe class="slide-deck" id="quartoframe" src="../slides/01-slides.html"></iframe>
```
```{r show-slide-tabs, echo=FALSE, results="asis"}
slide_win_button("/slides/01-slides")
```
