---
title: "4. Version Control"
date: 2023-09-19
date-format: full
---

```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## This week ...

Git!

## Sample project

- The sample project used in the slides can be found at <https://github.com/kjhealy/covid-project>

## Background and Related Reading

- @chacon14:_pro_git
- @sylor-miller21:_oh_shit_git

- [Happy Git with R](https://happygitwithr.com) provides detailed instructions on getting Git and GitHub set up to work smoothly for R users.

## Slides

```{=html}
<script type="application/javascript">

function resizeIFrameToFitContent( iFrame ) {

   iFrame.width  = document.getElementById("quarto-document-content").clientWidth;
   iFrame.height  = (document.getElementById("quarto-document-content").clientWidth * 0.5625)
}

window.addEventListener('DOMContentLoaded', function(e) {

    var iFrame = document.getElementById( 'quartoframe' );
    resizeIFrameToFitContent( iFrame );
    } );

</script>
<iframe class="slide-deck" id="quartoframe" src="../slides/03-slides.html"></iframe>
```

```{r show-slide-tabs, echo=FALSE, results="asis"}
slide_win_button("/slides/04-slides")
```
