---
title: "05. Tables and Tidy Data"
date: last-modified
date-format: full
---

```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## This week ...

We'll learn about the core of working with data: doing things to tables.

## Required Reading

- @wickham23:_r_data_scien.

[Read the text online.](https://r4ds.hadley.nz/) Review or redo [Chapter 3](https://r4ds.hadley.nz/data-transform) and [Chapter 5](https://r4ds.hadley.nz/data-tidy); read and work through as much of [Chapters 12-14](https://r4ds.hadley.nz/transform) as you can.


## Examples

[This week's examples and demos](/example/05-example-dplyr.qmd).


## Assignment

[This week's assignment](/assignment/05-assignment-dplyr.qmd).

## Slides

```{=html}
<script type="application/javascript">

function resizeIFrameToFitContent( iFrame ) {

   iFrame.width  = document.getElementById("quarto-document-content").clientWidth;
   iFrame.height  = (document.getElementById("quarto-document-content").clientWidth * 0.5625)
}

window.addEventListener('DOMContentLoaded', function(e) {

    var iFrame = document.getElementById( 'quartoframe' );
    resizeIFrameToFitContent( iFrame );
    } );

</script>
<!--iframe class="slide-deck" id="quartoframe" src="../slides/05-slides-r-dplyr.html"></iframe-->
```

```{r show-slide-tabs, echo=FALSE, results="asis"}
#slide_win_button("/slides/05-slides-r-dplyr")
```


```{=html}
<!--iframe class="slide-deck" id="quartoframe" src="../slides/05-slides-r-reshaping-data.html"></iframe-->
```

```{r show-slide-tabs2, echo=FALSE, results="asis"}
#slide_win_button("/slides/05b-slides-r-reshaping-data")
```
