---
title: "Sociol 703: Modern Plain Text Computing"
author:
  - name: Kieran Healy
    email: kieran.healy@duke.edu
    affiliations:
      - id: duke
        name: Duke University
date: "2026-08-19"
date-format: long
format:
  html:
    code-tools: false
  minion-pdf: default
editor:
  markdown:
    wrap: 72
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

# About this course

This course is an introduction to modern plain-text methods of data analysis,
data management, and coding. It is required for first-year graduate students in
the Sociology department. It introduces a collection of computing tools and
techniques that are widely used in the department, across the social sciences,
and beyond. We will learn to use these tools and also learn why they exist and
why they are important for producing work that is reliable, reproducible, and
open to inspection.

{{< include ../_motivation.qmd >}}

# Reading

Required reading from books and articles will be provided on [the course
website](https://mptc.io), Canvas, or (in most cases) will be freely
available online. Useful texts to acquire in hardcopy or to bookmark
include:

-   [@wickham23:_r_data_scien]
-   [@janssens21:_data_science_command_line]
-   [@ismaykim19:modern]
-   [@chacon14:_pro_git]
-   [@healy:2019]
-   [@friedl06:_master_regul_expres]
-   [@landau22:_r]
-   [@wickhambryan:2023]
-   [@christensen19:_trans_reprod_social_scien_resear]

# Software

We will do all most of our work class using Unix-style command line
tools, [R](https://cran.r-project.org/), and
[RStudio](https://www.rstudio.com/). [R](https://cran.r-project.org/) is
a freely-available programming language that is designed for statistical
computing and widely used across the natural and social sciences, as
well as in the world of "data science" generally.
[RStudio](https://www.rstudio.com/) is an integrated development
environment, or IDE, for R, a kind of control center from which you can
manage the engine-room of R itself. It is also freely available.

# Website, Canvas, and Slack

The course website is at <https://mptc.io>. Each week, slides, readings, and
other class material will be posted there along with additional examples and the
problem set due the following week. We will use Duke's Learning CMS, Canvas, for
submission of assignments and to host some readings. There is also a Slack
workspace for the course. Details about joining it will be provided via email.

# Weekly Schedule

The schedule is shown in @tbl-schedule. It is subject to change.

{{< include ../_weekly-schedule.qmd >}}

# Expectations

This is a graduate seminar. I take it for granted that you have a basic interest
in the material, an enthusiastic attitude toward participation, and a respectful
attitude to everyone in the room. I expect you to attend each meeting, do the
required reading and assignments thoroughly and on time, and participate
actively. Participating actively means contributing to class discussion and
problem-solving, something that involves both speaking and listening. Do not
silently wander off during class, as if the person speaking in front of you was
on a screen. Each class meeting will have a short break in the middle.

The main purpose of the first year graduate sequence is to teach you some core
things about the field that are either required for you to do good work, or
extremely useful toward that end, but which you do not already know. This has
some implications that might not be immediately obvious. First, I am not making
you read or do things in order to waste your time or haze you in some weird
fashion. Second, your role in the class is to try to learn things you don't
already know and not, for example, to try to impress me, your peers, or yourself
with how clever you are. Third, this point also applies to my role as the
instructor. Fourth, the people in the room---including me---are not your
competitors or enemies; they are your interlocutors. Academic disciplines are
just highly-structured, long-running conversations involving specialized
show-and-tell and question-and-answer formats. This is where you start learning
what the conversation topics are, what you need to know in order to make
something useful, and how to begin making your own contributions. So please,
trust this process. Everything will go better if you do.

# Required work and assessment

Weekly **Class Participation** (50% of final grade) and **Assignments** (50% of
final grade) will let you reflect on the reading and practice your skills.
Assignments due by end of day the *Friday* after the class they are assigned.
Submit assignments via Canvas.

# Course policies

-   Attendance is required, and important. I am a reasonable person; if
    you need to be absent please *let me know in advance* insofar as
    that is possible.
-   Do the assigned readings in advance of class.
-   Submit problem sets, or other assignments, on time.
-   Do not use AI tools to complete assignments unless I explicitly say that you
may do so. We'll discuss them, their uses, and their limitations as we go. These
tools are new, powerful, and changing very fast. They play an increasing role in
many aspects of the work we do, especially insofar as it touches on how we write
and work with code and how we manage some of the mundane tasks associated with
managing data. But if you use them for an assigment when I asked you not to, you
will get an F for the course. I am not joking. The point of this seminar---the
whole reason it is required---is for you to learn how to do some things for
yourself, and to understand what it is you are doing. By the end of the course
we will likely be using AI tools of various kinds to help us out, because AI can
be very handy once we know what we are doing. But first we have to know what
we are doing.


# Duke community standard

Like all classes at the university, this course is conducted under the
Duke Community Standard. Duke University is a community dedicated to
scholarship, leadership, and service and to the principles of honesty,
fairness, respect, and accountability. Citizens of this community commit
to reflect upon and uphold these principles in all academic and
nonacademic endeavors, and to protect and promote a culture of
integrity. To uphold the Duke Community Standard you will not lie,
cheat, or steal in academic endeavors; you will conduct yourself
honorably in all your endeavors; and you will act if the Standard is
compromised.
